apiVersion: apps/v1
kind: Deployment

metadata:
  name: app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app

    spec:
      containers:
      - name: app
        image: node:18
        command: ["sleep","3600"]

        env:
        - name: DB_HOST
          value: postgres-service

        - name: DB_NAME
          value: appdb

        - name: DB_USER
          value: appuser

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password

        ports:
        - containerPort: 3000